version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always 
    ports:
      - 3307:3306
    expose:
      - 3307
    env_file:
      - ./.env
  node_app:
    container_name: node
    build: . 
    depends_on:
      - db 
    env_file:
      - ./.env 
    ports:
      - 5001:5001